### ISSUE TITLE
Undeclared dependency on capistrano-bundler

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlss-capistrano#11]
If you don't `require 'capistrano/bundler'` in your application you will get:
```
cap stage deploy
(Backtrace restricted to imported tasks)
cap aborted!
Don't know how to build task 'bundler:install' (see --tasks)
/Users/jcoyne/workspace/dlss-labs/rialto-etl/Capfile:36:in `require'
/Users/jcoyne/workspace/dlss-labs/rialto-etl/Capfile:36:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jcoyne** [comment]
Actually an upstream bug: https://github.com/cbeer/capistrano-bundle_audit/pull/8

**Comment by mjgiarlo** [comment]
@jcoyne given https://github.com/cbeer/capistrano-bundle_audit/pull/8, can/should this be closed? or do you think dlss-capistrano should add cap-bundler as a dep?
