### ISSUE TITLE
Remove bundler 2-style configuration task

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dlss-capistrano#22]
This is finally supported in capistrano-bundler as of version 2.0.0, thanks to https://github.com/capistrano/bundler/pull/122.

**Comment by jcoyne** [comment]
That upgrade is blocked by the pinning of capistrano-bundler in capistrano-bundle_audit: https://github.com/cbeer/capistrano-bundle_audit/blob/master/capistrano-bundle_audit.gemspec#L21

**Comment by mjgiarlo** [comment]
I believe this is now done.
